import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
import { eq, and } from 'drizzle-orm';
import { getDb } from '../db/client.js';
import { concepts, runs } from '../db/schema.js';
import { getDomainById } from '../experiments/stage1/domains.js';
import { xDraftRequestSchema } from '@velanza/shared';

export const xPublisherRouter = new Hono();

const TEMPLATE_ES = `🪟 Nuevo concepto generado por diálogo entre IAs:

{word} ({domain})

{definition}

Etimología: {etymology}

#PostGPT #Lexicalizacion #IA`;

const TEMPLATE_EN = `🪟 New concept generated by dialogue between AIs:

{word} ({domain})

{definition}

Etymology: {etymology}

#PostGPT #Lexicalization #AI`;

const X_CHAR_LIMIT = 280;

function fillTemplate(template: string, vars: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (_, key) => vars[key] ?? '');
}

xPublisherRouter.post('/draft', zValidator('json', xDraftRequestSchema), async (c) => {
  const db = getDb();
  const { conceptId, language } = c.req.valid('json');

  const concept = await db.query.concepts.findFirst({
    where: eq(concepts.id, conceptId),
  });
  if (!concept) return c.json({ error: 'Not found' }, 404);

  const run = await db.query.runs.findFirst({
    where: eq(runs.id, concept.runId),
  });
  const domain = run ? getDomainById(run.domain) : undefined;
  const domainLabel = domain
    ? language === 'es'
      ? domain.label.es
      : domain.label.en
    : (run?.domain ?? '');

  const template = language === 'es' ? TEMPLATE_ES : TEMPLATE_EN;
  const text = fillTemplate(template, {
    word: concept.word,
    domain: domainLabel,
    definition: concept.definition,
    etymology: concept.etymology,
  });

  const exceedsLimit = text.length > X_CHAR_LIMIT;
  const url = `https://x.com/intent/tweet?text=${encodeURIComponent(text)}`;

  await db
    .update(concepts)
    .set({
      draftGeneratedAt: Math.floor(Date.now() / 1000),
      ...(language === 'es' ? { draftTextEs: text } : { draftTextEn: text }),
    })
    .where(eq(concepts.id, conceptId));

  return c.json({ text, url, exceedsLimit, charCount: text.length, charLimit: X_CHAR_LIMIT });
});
